import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import Header from "../components/Header";
import Providers from "./providers";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-slate-100 text-dark-blue`}>
        <Providers>
          <div className="">
            <div className="sm:mt-4">
              <Header />
            </div>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
